bfMarca901="""
                            <option id=0></option>
                            <option id=6>Chevrolet</option>
                            <option id=9>Citroen/DS</option>
                            <option id=3>Fiat</option>
                            <option id=5>Ford</option>
                            <option id=1>Peugeot</option>
                            <option id=2>Renault</option>
                            <option id=10>Toyota</option>
                            <option id=4>Volkswagen</option>
                            <option id=0></option>
                            <option id=7>Alfa Romeo</option>
                            <option id=12>Audi</option>
                            <option id=119>BAIC</option>
                            <option id=31>BMW / Mini</option>
                            <option id=19>Daewoo</option>
                            <option id=37>Daihatsu</option>
                            <option id=34>Mazda</option>
                            <option id=28>Mercedes Benz</option>
                            <option id=36>Mitsubishi</option>
                            <option id=33>Nissan</option>
                            <option id=0></option>
                            <option id=58>Aleko</option>
                            <option id=79>AMC</option>
                            <option id=71>Austin</option>
                            <option id=64>Autobianchi</option>
                            <option id=47>Buick</option>
                            <option id=103>Cadillac</option>
                            <option id=570>CFMOTO</option>
                            <option id=109>Chery</option>
                            <option id=13>Chrysler/Jeep</option>
                            <option id=97>Coradir/TITO</option>
                            <option id=18>Dacia</option>
                            <option id=30>Datsun</option>
                            <option id=98>De Carlo</option>
                            <option id=81>De Soto</option>
                            <option id=20>Di Tella</option>
                            <option id=66>DKW</option>
                            <option id=17>Dodge/RAM</option>
                            <option id=90>Eagle</option>
                            <option id=54>FSO Polonez</option>
                            <option id=117>Geely</option>
                            <option id=25>Honda/Acura</option>
                            <option id=101>Hudson</option>
                            <option id=99>Hummer</option>
                            <option id=29ra>Hyundai</option>
                            <option id=39ra>Ika</option>
                            <option id=78ra>Isard</option>
                            <option id=26ra>Isuzu</option>
                            <option id=55ra>Jaguar</option>
                            <option id=92ra>John Deere</option>
                            <option id=32ra>Kia</option>
                            <option id=41ra>Lada</option>
                            <option id=48ra>Lancia</option>
                            <option id=52ra>Lexus</option>
                            <option id=116>Lifan</option>
                            <option id=107>Lincoln</option>
                            <option id=50>Maserati</option>
                            <option id=68>Mercury</option>
                            <option id=56>MG</option>
                            <option id=88>Morris</option>
                            <option id=84>NSU</option>
                            <option id=93>Oldsmobile</option>
                            <option id=53>Oltcit</option>
                            <option id=40>Opel</option>
                            <option id=69>Plymouth</option>
                            <option id=86>Pontiac</option>
                            <option id=51>Porsche</option>
                            <option id=46>Proton</option>
                            <option id=15>Rambler</option>
                            <option id=59>Rolls Royce</option>
                            <option id=14>Rover</option>
                            <option id=43>Saab</option>
                            <option id=11>Seat</option>
                            <option id=112>Simca</option>
                            <option id=57>Skoda</option>
                            <option id=24>Subaru</option>
                            <option id=23>Suzuki</option>
                            <option id=572>SWM</option>
                            <option id=63>Tavria</option>
                            <option id=16>Torino</option>
                            <option id=82>Triumph</option>
                            <option id=21>Valiant</option>
                            <option id=22>Volvo</option>
                            <option id=62>Willys</option>
"""

bfMarca907="""
                            <option id=0></option>
                            <option id=	119>BAIC</option>
                            <option id=	7>Alfa Romeo</option>
                            <option id=	44>Aro</option>
                            <option id=	42>Asia</option>
                            <option id=	12>Audi</option>
                            <option id=	111>Beijing</option>
                            <option id=	67>Bertone</option>
                            <option id=	31>BMW/Mini</option>
                            <option id=	75>Changan</option>
                            <option id=	109>Chery</option>
                            <option id=	6>Chevrolet</option>
                            <option id=	13>Chrysler/Jeep</option>
                            <option id=	9>Citroen/DS</option>
                            <option id=	19>Daewoo</option>
                            <option id=	37>Daihatsu</option>
                            <option id=	120>DFSK</option>
                            <option id=	17>Dodge/RAM</option>
                            <option id=	125>FAW</option>
                            <option id=	3>Fiat</option>
                            <option id=	5>Ford</option>
                            <option id=	117>Geely</option>
                            <option id=	106>GMC</option>
                            <option id=	123>Haval</option>
                            <option id=	25>Honda/Acura</option>
                            <option id=	99>Hummer</option>
                            <option id=	29>Hyundai</option>
                            <option id=	39>Ika</option>
                            <option id=	83>Infinity</option>
                            <option id=	105>International</option>
                            <option id=	26>Isuzu</option>
                            <option id=	121>JAC Motors</option>
                            <option id=	55>Jaguar</option>
                            <option id=	127>Jetour</option>
                            <option id=	32>Kia</option>
                            <option id=	41>Lada</option>
                            <option id=	27>Land Rover</option>
                            <option id=	52>Lexus</option>
                            <option id=	116>Lifan</option>
                            <option id=	107>Lincoln</option>
                            <option id=	50>Maserati</option>
                            <option id=	34>Mazda</option>
                            <option id=	28>Mercedes Benz</option>
                            <option id=	68>Mercury</option>
                            <option id=	36>Mitsubishi</option>
                            <option id=	33>Nissan</option>
                            <option id=	40>Opel</option>
                            <option id=	1>Peugeot</option>
                            <option id=	51>Porsche</option>
                            <option id=	2>Renault</option>
                            <option id=	122>Shineray/SWM</option>
                            <option id=	38>Ssangyong</option>
                            <option id=	24>Subaru</option>
                            <option id=	23>Suzuki</option>
                            <option id=	45>Tata</option>
                            <option id=	10>Toyota</option>
                            <option id=	115>UAZ/VAZ</option>
                            <option id=	4>Volkswagen</option>
                            <option id=	22>Volvo</option>
                            <option id=	62>Willys</option>
"""